name: CI - Run Tests on Staging and Merge to Deploy
on:
  push:
    branches: 
      - 'staging'
jobs:
  setup-and-run-ui-tests:
    name: Run UI Tests - Chrome - Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: Start Server
        run: |
          cd ./backend
          npm ci 
          export SESSION_TOKEN=${{ secrets.SESSION_TOKEN }}
          export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          npx tsc && node out/src/app.js &

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v2
        with:
          config: 'baseUrl=http://localhost:5000'
          env: 'username="${{ secrets.TEST_USERNAME }}",password=${{ secrets.TEST_USER_PASSWORD }},xtoken=${{ secrets.TEST_USER_XTOKEN }},apiUrl=http://localhost:8080,CIWait=true'
          # config: 'viewportWidth=375,viewportHeight=812,baseUrl=http://localhost:5000'
          start: npm run frontend:start
          wait-on: 'http://localhost:5000, http://localhost:8080/'
          wait-on-timeout: 120
          browser: chrome
          headless: true
          working-directory: tests
  #         group: 'UI - Chrome - Staging'
  #         record: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  merge-staging-to-deploy:
    timeout-minutes: 2
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/staging' }}
    runs-on: ubuntu-latest
    needs: setup-and-run-ui-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: Set Git config
        run: |
            git config --local user.email "exodus[bot]@exodus.noreply.github.com"
            git config --local user.name "exodus[bot]"
      - name: Merge staging to deploy
        run: |
            git checkout deploy
            git pull
            git merge --no-ff staging -m "Auto-merge staging to deploy"
            git push
